#!/bin/bash
#SBATCH --time=3-00:00:00
#SBATCH --job-name=ionwake
#SBATCH --partition=max1
#SBATCH --error=error
#SBATCH --output=log
#SBATCH -N 1
#SBATCH -n 10
#SBATCH --chdir=data1
export OMP_NUM_THREADS=$SBATCH_NUM_PPN
./project data1
