#!/bin/bash
mkdir $1
export PROJECTNAME=$1/project
make clean
make
> launch 

echo "#!/bin/bash" >> launch
echo "#SBATCH --time=2:00:00" >> launch
echo "#SBATCH --job-name=mpi-ionwake" >> launch
echo "#SBATCH --ntasks=2" >> launch
echo "#SBATCH --cpus-per-task=4" >> launch
echo "#SBATCH --nodes=2" >> launch
echo "#SBATCH --ntasks-per-node=1" >> launch 
echo "#SBATCH --error=error" >> launch
echo "#SBATCH --output=log" >> launch
echo "#SBATCH --chdir=$1" >> launch

echo "srun --mpi=pmix ./project" >> launch

chmod +x launch
sbatch launch --gres=none
