#!/bin/bash
for (( i=0; i<$1; i++ )); do
	let "c = $i * $2"
	export density_file="data/density_t"$c".dat"
	export density_vtkfile="data/density_t"$c".vti"
	export potential_file="data/potential_t"$c".dat"
	export potential_vtkfile="data/potential_t"$c".vti"
	export velocity_file="data/velocity_t"$c".dat"
	export velocity_vtkfile="data/velocity_t"$c".vti"
	data/gradient $density_file $density_vtkfile
	data/gradient $potential_file $potential_vtkfile
	data/velocity_field $velocity_file $velocity_vtkfile
done
	
